apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: springboot
  labels:
    app: springboot
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: springboot
  type: LoadBalancer
